# https://taskfile.dev
version: '3'
tasks:
  dev:
    desc: Start the application in development mode
    cmds:
      - nest start --watch

  lint:
    desc: Run the linter
    cmds:
      - pnpm lint

  format:
    desc: Format the sources
    cmds:
      - pnpm format

  seed:
    desc: Drop the database and insert the seed data
    cmds:
      - pnpm seed

  build:
    desc: Build the application
    cmds:
      - nest build
